### ISSUE TITLE
`serialize` feature doesn't compile even without any changes

### ISSUE THREAD

**Issue by Brogolem35** [Kixiron/lasso#50]
## I tried this code

Code:
```rust
pub struct MarkovChain {
	items: HashMap<Vec<Spur>, ChainItem>,
	state_size: usize,
	regex: Regex,
	cache: Rodeo,
}
```

Cargo.toml
```toml
[package]
name = "markov_str"
version = "0.1.0"
authors = ["brogolem35"]
edition = "2021"
description = "Markov Chain implementation optimized for text generation."
license = "MIT"
repository = "https://github.com/Brogolem35/markov_str"
keywords = ["markov", "markov-chain", "text-generation"]
categories = ["text-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serialize = ["serde", "lasso/serialize", "hashbrown/serde"]

[dependencies]
hashbrown = "0.14.5"
lasso = {version = "0.7.2", features = ["ahasher", "inline-more"]}
rand = "0.8.5"
regex = "1.10.6"
serde = {version = "1.0.208", features = ["derive"], optional = true, default-features = false}

# [target.'cfg(not(target_env = "msvc"))'.dependencies]
# tikv-jemallocator = "0.6"

[package.metadata.clippy]
# This sets all pedantic lints to be treated as errors
deny = ["clippy::pedantic"]
```

## I expected this to happen

Code should have compiled as there have been compile with no issues.

## Instead this happened

Compilation fails even though I changed no code other than enabling the feature.

### Meta

version = "0.7.2", features = ["ahasher", "inline-more"]

Rustc version:

```sh
> rustc -Vv
rustc 1.80.0 (051478957 2024-07-21)
binary: rustc
commit-hash: 051478957371ee0084a7c0913941d2a8c4757bb9
commit-date: 2024-07-21
host: x86_64-unknown-linux-gnu
release: 1.80.0
LLVM version: 18.1.7
```
